openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      title: JSON API Schema
      description: >-
        This is a schema for responses in the JSON API format. For more, see
        http://jsonapi.org
      type: object
      properties:
        status:
          description: >-
            The HTTP status code applicable to this problem, expressed as a
            string value.
          type: string
        code:
          description: 'An application-specific error code, expressed as a string value.'
          type: string
    GetProductsListResponse:
      title: Products
      description: List of products
      type: array
      items:
        type: object
        properties:
          count:
            type: integer
            description: Number of products in stock
            minimum: 0
          description:
            type: string
            description: Description of the product
          image_url:
            type: string
            description: Url of the product image
          id:
            description: uuid
            type: string
            format: uuid
          price:
            description: Product's price
            type: integer
            minimum: 0
          title:
            description: Product title
            type: string
    GetProductsListRequest:
      title: Empty Schema
      type: object
    GetProductResponse:
      title: Product
      description: A product in the catalog
      type: object
      properties:
        count:
          type: integer
          description: Number of products in stock
          minimum: 0
        description:
          type: string
          description: Description of the product
        image_url:
          type: string
          description: Url of the product image
        id:
          description: uuid
          type: string
          format: uuid
        price:
          description: Product's price
          type: integer
          minimum: 0
        title:
          description: Product title
          type: string
    GetProductRequest:
      title: Empty Schema
      type: object
    CreateProductResponse:
      title: Product
      description: A product in the catalog
      type: object
      properties:
        description:
          type: string
          description: Description of the product
        image_url:
          type: string
          description: Url of the product image
        id:
          description: uuid
          type: string
          format: uuid
        price:
          description: Product's price
          type: integer
          minimum: 0
        title:
          description: Product title
          type: string
    CreateProductRequest:
      title: Product
      type: object
      properties:
        description:
          type: string
          description: Description of the product
        image_url:
          type: string
          description: Url of the product image
        price:
          description: Product's price
          type: integer
          minimum: 0
        title:
          description: Product title
          type: string
  securitySchemes: {}
info:
  title: Products API
  description: Products API
  version: '1'
paths:
  /products:
    get:
      operationId: getProductsList
      summary: Get all products
      description: Returns the list of all products
      responses:
        '200':
          description: List of all products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductsListResponse'
        '500':
          description: Error getting list of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      operationId: createProduct
      summary: Create new product
      description: Returns the newly created product
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error creating product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/products/{productId}':
    get:
      operationId: getProductsById
      summary: Get product by id
      description: Returns product info
      parameters:
        - name: 'productId'
          in: 'path'
          description: 'This is the product id'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: Product info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductResponse'
        '500':
          description: Error getting list of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
